config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:omniauth_callbacks, :sessions], controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :media_items, only: [:index]
  root :to => "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  validates :uid, :provider, :token, presence: true
  validates_uniqueness_of :uid, :scope => :provider

  belongs_to :user

  scope :instagram, -> {where(provider: :instagram)}

  def update_info(auth)
    self.token = auth[:credentials][:token]
  end

  def self.check_provider_existance(auth_hash)
    authentication = Authentication.where(provider: auth_hash[:provider], uid: auth_hash[:uid]).first
    authentication ||= Authentication.new()
  end
end

app/models/concerns/instagram_client.rb
class InstagramClient
  def initialize(access_token)
    @client = Instagram.client(:access_token => access_token)
    @recent_media_items = nil
  end

  def recent_media
    fetch_recent_media
  end

  #######
  private
  #######

  def fetch_recent_media
    @recent_media_items ||= @client.user_recent_media
    @recent_media_items
  end
end

app/models/concerns/media_item.rb
class MediaItem
  attr_accessor :standard_resolution_url, :low_resolution_url

  def initialize(standard_resolution_url, low_resolution_url)
    @standard_resolution_url = standard_resolution_url
    @low_resolution_url = low_resolution_url
  end

  def self.load_collection(items)
    list = []
    items.each do |item|
      list << MediaItem.new(item.images.standard_resolution.try(:url), item.images.low_resolution.try(:url))
    end
    list
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:instagram]

  has_many :authentications

  def update_info(auth)
    self.username = auth[:extra][:raw_info][:username]
  end

  def link_to_social_networks(auth)
    self.authentications.build(provider: auth[:provider], uid: auth[:uid], token: auth[:credentials][:token])
    self
  end

  def force_remember_me
    self.password = Devise.friendly_token[0,20]
    self.devise_pwd = true
  end

  def instagram_token
    self.authentications.instagram.first.try(:token)
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/omniauth_callbacks.rb
class OmniauthCallbacks

  def initialize(provider, auth_response)
    @provider = provider
    @auth = auth_response
  end

  def load_user
    check_provider_and_return_user
  end

  #######
  private
  #######

  def check_provider_and_return_user
    user = User.new
    case @provider
    when "instagram"
      authentication = Authentication.check_provider_existance(@auth)
      if !authentication.new_record?
        user = authentication.user
        authentication.update_info(@auth)
        authentication.save
      else
        user = User.new
        user = user.link_to_social_networks(@auth)
        user.force_remember_me
      end
    end
    user
  end
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
	# before_action :authenticate_user!

	def index
		instagram_client = InstagramClient.new(current_user.instagram_token)
		@media_items = MediaItem.load_collection(instagram_client.recent_media)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def instagram
    social_linking
  end

  def social_linking
    auth = request.env["omniauth.auth"]
    provider = auth[:provider]
    user = OmniauthCallbacks.new(provider, auth).load_user
    user.update_info(auth)
    user.save!
    signin_with_social_network(user, :signed_in, provider)
  end

  def failure
    redirect_to root_path, alert: params[:error]
  end

  #######
  private
  #######

  def signin_with_social_network(user, type, provider)
    user.remember_me = true
    sign_in_and_redirect user, :event => :authentication #this will throw if user is not activated
    set_flash_message(:notice, type, :kind => provider) if is_navigational_format?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% if notice %>
<div class="alert alert-success">
  <strong>Success!</strong> <%= notice %>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger">
  <strong>Alert!</strong> <%= alert %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>InstagramRails</title>
    <link rel="icon" href="/favicon.ico">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', 'album', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Rails application, which allows the user to view their Instagram pictures.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <% if current_user %>
              <h4 class="text-white">Hi, <%= current_user.username %></h4>
              <ul class="list-unstyled">
                <li>
                  <%= link_to('My Pictures', media_items_path, class:"text-white") %>
                </li>
                <li>
                  <%= link_to('Sign Out', destroy_user_session_path, method: :delete, class:"text-white") %>
                </li>
              </ul>
              <% else %>
              <h4 class="text-white">Hi, </h4>
              <ul class="list-unstyled">
                <li>
                  <%= link_to "Login", omniauth_authorize_path(:user, :instagram), class: "text-white" %>
                </li>
              </ul>
              <% end %>

            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="/" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>InstagramRails</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <%= render partial: "/layouts/flash_messages" %>

    <%= yield %>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>InstagramRails &copy;</p>
      </div>
    </footer>
  </body>
</html>

app/views/media_items/index.html.erb
<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <% @media_items.each do |media_item| %>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" src="<%= media_item.low_resolution_url %>">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a type="button" href="<%= media_item.standard_resolution_url %>" target="_blank" class="btn btn-sm btn-outline-secondary">View</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <% unless @media_items.any? %>
          <div class="col-md-12">
            <div class="card mb-12 box-shadow">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <h2>No Media items were found</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/pages/home.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Instagram Example</h1>
      <p class="lead text-muted">
        <!-- Rails application, which allows the user to view their Instagram pictures.<br> -->
        <% unless current_user %>
        Instagram application still in Sandbox mode, use the following account to test the application<br/><br/>
        Username: testintgmrails <br/>
        Password: instagram_rails <br/>
        <% end %>
      </p>

      <p>
        <% if current_user %>
          <%= link_to('My Pictures', media_items_path, class:"btn btn-primary my-2") %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"btn btn-secondary my-2") %>
        <% else %>
          <%= link_to "Login with Instagram", omniauth_authorize_path(:user, :instagram), class: "btn btn-primary my-2" %>
        <% end %>
      </p>
    </div>
  </section>
</main>